### ISSUE TITLE
Not working on Xcode 9.2 and iOS 11.2

### ISSUE THREAD

**Issue by hankhong1205** [clappr/clappr-ios#182]
I simply added clappr to the project and tried to run the project, but I got following errors.
Does it support iOS 11?
```
INFO [Clappr] loading with ["sourceUrl": "http://clappr.io/highline.mp4"]
INFO [Loader] plugins:
 - playback: ["AVPlayback", "NoOp"]
 - container: ["poster", "spinner"]
 - core: []
 - mediaControl: MediaControl
2018-03-02 00:29:04.133083+0800 ClapprDemoApp[87621:34003656] [MediaRemote] [AVOutputContext] WARNING: AVF context unavailable for sharedAudioPresentationContext
2018-03-02 00:29:04.133412+0800 ClapprDemoApp[87621:34003656] [MediaRemote] [AVOutputContext] WARNING: AVF context unavailable for +[MRAVOutputContext createOutputContextWithUniqueIdentifier:]
2018-03-02 00:29:04.356727+0800 ClapprDemoApp[87621:34003729] Error loading /Library/Audio/Plug-Ins/HAL/BartenderAudioPlugIn.plugin/Contents/MacOS/BartenderAudioPlugIn:  dlopen(/Library/Audio/Plug-Ins/HAL/BartenderAudioPlugIn.plugin/Contents/MacOS/BartenderAudioPlugIn, 262): no suitable image found.  Did find:
	/Library/Audio/Plug-Ins/HAL/BartenderAudioPlugIn.plugin/Contents/MacOS/BartenderAudioPlugIn: mach-o, but not built for iOS simulator
2018-03-02 00:29:04.357089+0800 ClapprDemoApp[87621:34003729] Cannot find function pointer New_SHP_PlugIn for factory <CFUUID 0x60400023a200> 834FC054-C1CC-11D6-BD01-00039315CD46 in CFBundle/CFPlugIn 0x7fbbb7c109f0 </Library/Audio/Plug-Ins/HAL/BartenderAudioPlugIn.plugin> (bundle, not loaded)
2018-03-02 00:29:04.359635+0800 ClapprDemoApp[87621:34003729] [MediaRemote] [AVOutputContext] WARNING: AVF context unavailable for +[MRAVOutputContext createOutputContextWithUniqueIdentifier:]
```

**Comment by nabilsafatli** [comment]
Hey @hankhong1205 ,

Sorry for taking so long to answer. We have already the support to `Xcode 9.2`.
Let us know if there is any other issue.
